### ISSUE TITLE
Remove references to external repositories

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1]
Remove this reference from redDwarf03 github repo.

```
A lightweight alternative to the Scaffold widget for avoiding the on-screen software keyboard. Automatically scrolls obscured TextField child widgets into view on focus
keyboard_avoider: 
    git:
      url: https://github.com/redDwarf03/keyboard_avoider.git
      ref: master
```
