### ISSUE TITLE
Update dependencies to use last version of inappwebview

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1100]
Update

- `archethic_dapp_framework_flutter`
- `archethic_wallet_client`
- `flutter_inappwebview: ^6.1.5`
- `web_socket_channel: ^3.0.1`
- `uuid: ^4.4.0`

Remove in `pubspec`
```
# Configuration added to make the webview work with Android and ios 18 - start
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios
  flutter_inappwebview_macos:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_macos
  webview_flutter_android: 3.16.1
# Configuration added to make the webview work with Android and ios 18 - end
```

Remove in `build.gradle`

```
   // Configuration added to make the webview work with Android - start
    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }
    // Configuration added to make the webview work with Android - end
```
